import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getDatabase,ref,get,set,update}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{firebaseConfig}from"./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app),ADMIN_EMAIL="dendi170898@gmail.com",GROUPS=["A","B","C","D"];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let teams={},groups={A:["","","",""],B:["","","",""],C:["","","",""],D:["","","",""]},matches={};
const defaultTeam=i=>({id:`T${i}`,name:`Tim ${i}`,group:"",main:0,win:0,draw:0,loss:0,gf:0,ga:0,gd:0,points:0});
const ensure16=raw=>{const out={};for(let i=1;i<=16;i++){const id=`T${i}`,x=raw?.[id]||{};out[id]={...defaultTeam(i),...(typeof x==="object"?x:{}),id,name:String(typeof x==="string"?x:(x.name||`Tim ${i}`))}}return out};
const emptyGroups=()=>({A:["","","",""],B:["","","",""],C:["","","",""],D:["","","",""]});
function normalizeGroups(raw){const out=emptyGroups(),used=new Set();for(const g of GROUPS){const v=Array.isArray(raw?.[g])?raw[g]:[];for(let i=0;i<4;i++){const id=v[i]||"";if(/^T([1-9]|1[0-6])$/.test(id)&&!used.has(id)){out[g][i]=id;used.add(id)}}}return out}
const pairings={1:[[0,1],[2,3]],2:[[0,2],[1,3]],3:[[0,3],[1,2]]};
const dates=[["2026-09-06","16:00"],["2026-09-12","13:30"],["2026-09-12","16:00"],["2026-09-13","08:00"],["2026-09-13","10:30"],["2026-09-13","13:30"],["2026-09-13","16:00"],["2026-09-19","13:30"],["2026-09-19","16:00"],["2026-09-20","08:00"],["2026-09-20","10:30"],["2026-09-20","13:30"],["2026-09-20","16:00"],["2026-09-26","13:30"],["2026-09-26","16:00"],["2026-09-27","08:00"],["2026-09-27","10:30"],["2026-09-27","13:30"],["2026-09-27","16:00"],["2026-10-03","13:30"],["2026-10-03","16:00"],["2026-10-04","08:00"],["2026-10-04","10:30"],["2026-10-04","13:30"]];
function msg(id,text,error=false){const e=$(id);if(e){e.textContent=text;e.className=`msg ${error?"err":"saveok"}`}}
function showLogin(){$("loginBox").classList.remove("hidden");$("adminBox").classList.add("hidden")}
function showAdmin(){$("loginBox").classList.add("hidden");$("adminBox").classList.remove("hidden");$("adminEmail").textContent=auth.currentUser?.email||""}
function readSelections(){const r=emptyGroups();for(const g of GROUPS)for(let i=0;i<4;i++)r[g][i]=$(`gteam_${g}_${i}`)?.value||"";return r}
function readStatsIntoTeams(next,sel){const fields=["main","win","draw","loss","gf","ga","gd","points"];const ids=[];for(const g of GROUPS)for(let i=0;i<4;i++){const id=sel[g][i];if(!id)continue;ids.push(id);const t={...(next[id]||defaultTeam(Number(id.slice(1))))};for(const f of fields){const el=$(`${f==='main'?'gm':f==='win'?'gw':f==='draw'?'gdr':f==='loss'?'gl':f}_${g}_${i}`);if(el){const n=el.value===""?0:Number(el.value);if(!Number.isFinite(n)||n<0)throw new Error(`Nilai ${f.toUpperCase()} di Grup ${g} baris ${i+1} tidak valid.`);t[f]=n}}t.group=g;next[id]=t}return ids}
function renderTeams16(){const body=$("teams16Admin");if(!body)return;body.innerHTML=Array.from({length:16},(_,i)=>{const t=teams[`T${i+1}`]||defaultTeam(i+1);return `<tr><td>${i+1}</td><td><input id="team16_T${i+1}" value="${esc(t.name)}" placeholder="Nama Tim ${i+1}"></td></tr>`}).join("")}
function renderGroups(){const root=$("groupsAdmin");if(!root)return;const opts=Array.from({length:16},(_,i)=>teams[`T${i+1}`]||defaultTeam(i+1));root.innerHTML=GROUPS.map(g=>`<div class="group"><h3>Grup ${g}</h3><div class="tablewrap"><table><thead><tr><th>No</th><th class="name">Nama Tim</th><th>Main</th><th>Menang</th><th>Seri</th><th>Kalah</th><th>GM</th><th>GK</th><th>SG</th><th>Poin</th></tr></thead><tbody>${Array.from({length:4},(_,i)=>{const id=groups[g]?.[i]||"",t=teams[id]||defaultTeam(i+1),v=k=>Number.isFinite(+t[k])?+t[k]:0;return `<tr><td>${i+1}</td><td class="name"><select id="gteam_${g}_${i}" data-group="${g}" data-slot="${i}"><option value="">— Pilih Tim —</option>${opts.map(o=>`<option value="${o.id}" ${o.id===id?"selected":""}>${esc(o.name)}</option>`).join("")}</select></td><td><input id="gm_${g}_${i}" type="number" min="0" value="${v("main")}"></td><td><input id="gw_${g}_${i}" type="number" min="0" value="${v("win")}"></td><td><input id="gdr_${g}_${i}" type="number" min="0" value="${v("draw")}"></td><td><input id="gl_${g}_${i}" type="number" min="0" value="${v("loss")}"></td><td><input id="gf_${g}_${i}" type="number" min="0" value="${v("gf")}"></td><td><input id="ga_${g}_${i}" type="number" min="0" value="${v("ga")}"></td><td><input id="gd_${g}_${i}" type="number" value="${v("gd")}"></td><td><input id="gp_${g}_${i}" type="number" min="0" value="${v("points")}"></td></tr>`}).join("")}</tbody></table></div></div>`).join("");
  root.querySelectorAll("select[data-group]").forEach(el=>el.addEventListener("change",()=>{const draft=readSelections(),seen=new Set();for(const g of GROUPS)for(const id of draft[g])if(id){if(seen.has(id)){el.value="";msg("groupsMsg","❌ Tim yang sama tidak boleh dipilih dua kali.",true);return}seen.add(id)}groups=normalizeGroups(draft);localStorage.setItem("ligakita_groups_draft",JSON.stringify(groups));refreshOptions();msg("groupsMsg","✏️ Pilihan berubah. Klik Simpan Semua Grup." )}));
  refreshOptions();
}
function refreshOptions(){const root=$("groupsAdmin");if(!root)return;const draft=readSelections(),taken=new Set();for(const g of GROUPS)for(const id of draft[g])if(id)taken.add(id);root.querySelectorAll("select[data-group]").forEach(el=>{const g=el.dataset.group,i=+el.dataset.slot,own=draft[g][i]||"";el.innerHTML='<option value="">— Pilih Tim —</option>'+Array.from({length:16},(_,n)=>teams[`T${n+1}`]||defaultTeam(n+1)).filter(t=>t.id===own||!taken.has(t.id)).map(t=>`<option value="${t.id}" ${t.id===own?"selected":""}>${esc(t.name)}</option>`).join("");el.value=own})}
function buildMatches(existing={}){const out={};let n=1;for(let round=1;round<=3;round++)for(const g of GROUPS){const m=groups[g]||[];for(const [a,b] of pairings[round]){const id=`M${n}`,old=existing[id]||{},[date,time]=dates[n-1]||["",""];out[id]={id,phase:"group",round,group:g,home:m[a]||"",away:m[b]||"",homeScore:old.homeScore??null,awayScore:old.awayScore??null,status:old.status||"scheduled",date:old.date||date,time:old.time||time,location:old.location||""};n++}}return out}
function renderMatches(){const root=$("adminMatches");if(!root)return;const list=Object.values(matches).filter(m=>m.phase==="group").sort((a,b)=>+a.id.slice(1)-+b.id.slice(1));const name=id=>teams[id]?.name||"-";root.innerHTML=list.map((m,i)=>`<div class="match"><div><b>${i+1}</b><small>Putaran ${m.round}</small></div><div><b>Grup ${esc(m.group)}</b></div><div><b>${esc(name(m.home))}</b></div><div>VS</div><div><b>${esc(name(m.away))}</b></div><input id="h${m.id}" type="number" min="0" value="${m.homeScore??""}"><input id="a${m.id}" type="number" min="0" value="${m.awayScore??""}"><input id="d${m.id}" type="date" value="${esc(m.date||"")}"><input id="tm${m.id}" type="time" value="${esc(m.time||"")}"><select id="s${m.id}"><option value="scheduled" ${m.status!=="finished"?"selected":""}>Terjadwal</option><option value="finished" ${m.status==="finished"?"selected":""}>Selesai</option></select><button type="button" data-match="${m.id}">Simpan</button></div>`).join("");root.querySelectorAll("[data-match]").forEach(b=>b.addEventListener("click",()=>saveMatch(b.dataset.match)))}
function renderAll(){renderTeams16();renderGroups();renderMatches()}
async function loadData(){try{const [ts,gs,ms]=await Promise.all([get(ref(db,"teams")),get(ref(db,"groups")),get(ref(db,"matches"))]);teams=ensure16(ts.exists()?ts.val():{});groups=normalizeGroups(gs.exists()?gs.val():JSON.parse(localStorage.getItem("ligakita_groups_draft")||"null")||{});matches=ms.exists()?ms.val():{};if(!Object.keys(matches).length){matches=buildMatches(matches)}renderAll()}catch(e){console.error(e);msg("teams16Msg",`❌ Firebase: ${e.code||""} ${e.message}`,true)}}
async function saveTeams16(){const b=$("saveTeams16");b.disabled=true;try{if(!auth.currentUser)throw new Error("Sesi login habis. Login lagi.");const next=ensure16(teams);for(let i=1;i<=16;i++)next[`T${i}`].name=($("team16_T"+i)?.value||"").trim()||`Tim ${i}`;await set(ref(db,"teams"),next);const v=await get(ref(db,"teams"));if(!v.exists())throw new Error("Verifikasi gagal: /teams kosong.");teams=ensure16(v.val());renderTeams16();renderGroups();renderMatches();msg("teams16Msg","✅ 16 Tim tersimpan ke Firebase.")}catch(e){console.error(e);msg("teams16Msg",`❌ SAVE 16 TIM GAGAL — ${e.code||""} ${e.message}`,true)}finally{b.disabled=false}}
async function saveGroups(){const b=$("saveGroups");b.disabled=true;try{if(!auth.currentUser)throw new Error("Sesi login habis. Login lagi.");
  const sel=readSelections(),next=ensure16(teams),seen=new Set();
  for(const g of GROUPS)for(let i=0;i<4;i++){const id=sel[g][i];if(!id)continue;if(seen.has(id))throw new Error(`${teams[id]?.name||id} dipilih lebih dari sekali.`);seen.add(id)}
  // Tidak lagi membatalkan SAVE hanya karena grup belum lengkap. Yang sudah diedit disimpan apa adanya.
  groups=normalizeGroups(sel);localStorage.setItem("ligakita_groups_draft",JSON.stringify(groups));
  readStatsIntoTeams(next,groups);
  for(let i=1;i<=16;i++){if(!next[`T${i}`].name)next[`T${i}`].name=`Tim ${i}`}
  const newMatches=buildMatches(matches);
  const payload={teams:next,groups:groups,matches:newMatches};
  msg("groupsMsg","⏳ Menyimpan ke Firebase...");
  await update(ref(db),payload);
  const [tv,gv,mv]=await Promise.all([get(ref(db,"teams")),get(ref(db,"groups")),get(ref(db,"matches"))]);
  if(!tv.exists()||!gv.exists()||!mv.exists())throw new Error("Verifikasi setelah SAVE gagal: data Firebase tidak lengkap.");
  teams=ensure16(tv.val());groups=normalizeGroups(gv.val());matches=mv.val();renderAll();msg("groupsMsg","✅ TERSIMPAN. Grup + data Main/Menang/Seri/Kalah/GM/GK/SG/Poin + jadwal sudah masuk Firebase.");
}catch(e){console.error("SAVE GROUP ERROR",e);msg("groupsMsg",`❌ SAVE GAGAL — ${e.code||""} ${e.message}`,true)}finally{b.disabled=false}}
async function saveMatch(id){try{const old=matches[id]||{},saved={...old,homeScore:$("h"+id).value===""?null:+$("h"+id).value,awayScore:$("a"+id).value===""?null:+$("a"+id).value,status:$("s"+id).value,date:$("d"+id).value,time:$("tm"+id).value};await set(ref(db,"matches/"+id),saved);matches[id]=saved;msg("matchesMsg",`✅ ${id} tersimpan.`)}catch(e){msg("matchesMsg",`❌ ${e.code||""} ${e.message}`,true)}}
async function calcStandings(){try{const stats={};for(let i=1;i<=16;i++)stats[`T${i}`]={main:0,win:0,draw:0,loss:0,gf:0,ga:0,gd:0,points:0};Object.values(matches).filter(m=>m.phase==="group"&&m.status==="finished"&&m.home&&m.away&&m.homeScore!=null&&m.awayScore!=null).forEach(m=>{const h=stats[m.home],a=stats[m.away];if(!h||!a)return;const hs=+m.homeScore,as=+m.awayScore;h.main++;a.main++;h.gf+=hs;h.ga+=as;a.gf+=as;a.ga+=hs;if(hs>as){h.win++;a.loss++;h.points+=3}else if(hs<as){a.win++;h.loss++;a.points+=3}else{h.draw++;a.draw++;h.points++;a.points++}h.gd=h.gf-h.ga;a.gd=a.gf-a.ga});const next=ensure16(teams);for(let i=1;i<=16;i++)Object.assign(next[`T${i}`],stats[`T${i}`]);await set(ref(db,"teams"),next);teams=next;renderTeams16();renderGroups();msg("groupsMsg","✅ Klasemen dihitung dan tersimpan.")}catch(e){msg("groupsMsg",`❌ ${e.code||""} ${e.message}`,true)}}
$("loginBtn").addEventListener("click",async()=>{const email=$("username").value.trim(),pass=$("password").value;msg("loginMsg","Memproses login...");try{if(!email||!pass)throw new Error("Isi email dan password.");const c=await signInWithEmailAndPassword(auth,email,pass);if(c.user.email!==ADMIN_EMAIL){await signOut(auth);throw new Error("Akun ini bukan akun admin.")}}catch(e){msg("loginMsg",`❌ ${e.code||""} ${e.message}`,true)}});
$("logout").addEventListener("click",()=>signOut(auth));$("saveTeams16").addEventListener("click",saveTeams16);$("saveGroups").addEventListener("click",saveGroups);$("calcStandings").addEventListener("click",calcStandings);onAuthStateChanged(auth,async user=>{if(user&&user.email===ADMIN_EMAIL){showAdmin();await loadData()}else showLogin()});
window.addEventListener("error",e=>console.error("LigaKita Admin error:",e.error||e.message));
