import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getDatabase, ref, get, update, set } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app),ADMIN_EMAIL="dendi170898@gmail.com";
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const groups=['A','B','C','D'];
const defaultNames=['ARCAK PUTRA','TIGER','FIT JUNIOR','SUKAMANAH UNITED','FAMILY','Tim 6','Tim 7','Tim 8','Tim 9','Tim 10','Tim 11','Tim 12','Tim 13','Tim 14','Tim 15','Tim 16'];
const schedule=[['M1','A','T1','T2','2026-09-06','16:00'],['M2','A','T3','T4','2026-09-12','13:30'],['M3','B','T5','T6','2026-09-12','16:00'],['M4','B','T7','T8','2026-09-13','08:00'],['M5','C','T9','T10','2026-09-13','10:30'],['M6','C','T11','T12','2026-09-13','13:30'],['M7','D','T13','T14','2026-09-13','16:00'],['M8','D','T15','T16','2026-09-19','13:30'],['M9','A','T1','T3','2026-09-19','16:00'],['M10','A','T2','T4','2026-09-20','08:00'],['M11','B','T5','T7','2026-09-20','10:30'],['M12','B','T6','T8','2026-09-20','13:30'],['M13','C','T9','T11','2026-09-20','16:00'],['M14','C','T10','T12','2026-09-26','13:30'],['M15','D','T13','T15','2026-09-26','16:00'],['M16','D','T14','T16','2026-09-27','08:00'],['M17','A','T1','T4','2026-09-27','10:30'],['M18','A','T2','T3','2026-09-27','13:30'],['M19','B','T5','T8','2026-09-27','16:00'],['M20','B','T6','T7','2026-10-03','13:30'],['M21','C','T9','T12','2026-10-03','16:00'],['M22','C','T10','T11','2026-10-04','08:00'],['M23','D','T13','T16','2026-10-04','10:30'],['M24','D','T14','T15','2026-10-04','13:30']];
const defaultTeams={};for(let i=1;i<=16;i++)defaultTeams['T'+i]={id:'T'+i,name:defaultNames[i-1],group:String.fromCharCode(65+Math.floor((i-1)/4))};
const defaultMatches={};schedule.forEach(([id,group,home,away,date,time])=>defaultMatches[id]={id,group,home,away,date,time,homeScore:null,awayScore:null,status:'scheduled'});
let teams={},standings={},matches={};
function idFor(g,n){return 'T'+(groups.indexOf(g)*4+n)}
function base(g){return [1,2,3,4].map(n=>{const id=idFor(g,n),t=teams[id]||defaultTeams[id],s=standings[g]?.[id]||{};return{id,name:t.name,played:s.played??0,wins:s.wins??0,draws:s.draws??0,losses:s.losses??0,gf:s.gf??0,ga:s.ga??0,gd:s.gd??0,pts:s.pts??0}})}
function teamName(id){return teams[id]?.name||defaultTeams[id]?.name||id}
function fmt(d,t){const x=new Date(d+'T00:00:00');return (isNaN(x)?d:x.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}))+' • '+t+' WIB'}
function hide(){$('loginBox').classList.remove('hidden');$('adminBox').classList.add('hidden')};function show(){$('loginBox').classList.add('hidden');$('adminBox').classList.remove('hidden');$('adminEmail').textContent=auth.currentUser?.email||''}
async function load(){const [t,s,m]=await Promise.all([get(ref(db,'teams')),get(ref(db,'standings')),get(ref(db,'matches'))]);teams=t.exists()?t.val():{};standings=s.exists()?s.val():{};matches=m.exists()?m.val():{};if(!Object.keys(teams).length){await update(ref(db,'teams'),defaultTeams);teams={...defaultTeams}}if(!Object.keys(matches).length){await update(ref(db,'matches'),defaultMatches);matches={...defaultMatches}}render()}
function renderGroups(){let html='';for(const g of groups){html+=`<div class="group"><h3>Grup ${g}</h3><div class="tablewrap"><table><thead><tr><th>No</th><th>Nama</th><th>Main</th><th>Menang</th><th>Seri</th><th>Kalah</th><th>GM</th><th>GK</th><th>SG</th><th>Poin</th></tr></thead><tbody>`;base(g).forEach((r,i)=>{html+=`<tr><td>${i+1}</td><td><input class="name" id="name_${r.id}" value="${esc(r.name)}"></td><td><input id="p_${r.id}" type="number" min="0" value="${r.played}"></td><td><input id="w_${r.id}" type="number" min="0" value="${r.wins}"></td><td><input id="d_${r.id}" type="number" min="0" value="${r.draws}"></td><td><input id="l_${r.id}" type="number" min="0" value="${r.losses}"></td><td><input id="gf_${r.id}" type="number" min="0" value="${r.gf}"></td><td><input id="ga_${r.id}" type="number" min="0" value="${r.ga}"></td><td><input id="gd_${r.id}" type="number" value="${r.gd}"></td><td><input id="pt_${r.id}" type="number" min="0" value="${r.pts}"></td></tr>`});html+='</tbody></table></div></div>'}$('groupsAdmin').innerHTML=html}
function renderMatches(){let html='<div class="match" style="font-weight:700;color:#9aa6c1"><span>No</span><span>Pertandingan</span><span>Tanggal</span><span>Skor 1</span><span>Skor 2</span><span>Status</span><span>Aksi</span></div>';schedule.forEach(([id,g,h,a,date,time],i)=>{const m=matches[id]||defaultMatches[id];html+=`<div class="match"><span>${i+1}</span><div><b>Grup ${g}: ${esc(teamName(h))} VS ${esc(teamName(a))}</b><small>${id}</small></div><span>${esc(fmt(date,time))}</span><input id="h_${id}" type="number" min="0" value="${m.homeScore??''}" placeholder="0"><input id="a_${id}" type="number" min="0" value="${m.awayScore??''}" placeholder="0"><select id="s_${id}"><option value="scheduled" ${m.status==='scheduled'?'selected':''}>Terjadwal</option><option value="live" ${m.status==='live'?'selected':''}>LIVE</option><option value="finished" ${m.status==='finished'?'selected':''}>Selesai</option></select><button onclick="saveMatch('${id}')">Simpan</button></div>`});$('adminMatches').innerHTML=html}
function render(){renderGroups();renderMatches()}
$('loginBtn').onclick=async()=>{try{const c=await signInWithEmailAndPassword(auth,$('username').value.trim(),$('password').value);if(c.user.email!==ADMIN_EMAIL){await signOut(auth);$('loginMsg').textContent='Akun bukan admin.'}}catch(e){$('loginMsg').textContent='Login gagal: '+e.message}};$('logout').onclick=()=>signOut(auth);
$('saveGroups').onclick=async()=>{const u={};for(const g of groups)for(let n=1;n<=4;n++){const id=idFor(g,n),name=$('name_'+id).value.trim()||('Tim '+id.slice(1));u['teams/'+id]={id,name,group:g};u['standings/'+g+'/'+id]={played:+$('p_'+id).value||0,wins:+$('w_'+id).value||0,draws:+$('d_'+id).value||0,losses:+$('l_'+id).value||0,gf:+$('gf_'+id).value||0,ga:+$('ga_'+id).value||0,gd:+$('gd_'+id).value||0,pts:+$('pt_'+id).value||0}}await update(ref(db),u);for(const g of groups)for(let n=1;n<=4;n++){const id=idFor(g,n);teams[id]=u['teams/'+id];standings[g]??={};standings[g][id]=u['standings/'+g+'/'+id]}render();$('groupsMsg').textContent='Grup A, B, C, D tersimpan. Nama grup otomatis dipakai di jadwal.';setTimeout(()=>$('groupsMsg').textContent='',3500)};
$('calcStandings').onclick=()=>{const c={};for(const g of groups){c[g]={};base(g).forEach(r=>c[g][r.id]={...r,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,pts:0});schedule.filter(x=>x[1]===g).forEach(([id,gg,h,a])=>{const m=matches[id]||{};if(m.homeScore==null||m.awayScore==null)return;const H=c[g][h],A=c[g][a],hs=+m.homeScore,as=+m.awayScore;if(!H||!A)return;H.played++;A.played++;H.gf+=hs;H.ga+=as;A.gf+=as;A.ga+=hs;if(hs>as){H.wins++;H.pts+=3;A.losses++}else if(hs<as){A.wins++;A.pts+=3;H.losses++}else{H.draws++;A.draws++;H.pts++;A.pts++}});Object.values(c[g]).forEach(r=>r.gd=r.gf-r.ga)}standings=c;renderGroups();$('groupsMsg').textContent='Klasemen sudah dihitung dari hasil pertandingan. Klik Simpan Semua Grup untuk menyimpan.'};
window.saveMatch=async id=>{const old=matches[id]||defaultMatches[id],h=$('h_'+id).value,a=$('a_'+id).value,s=$('s_'+id).value,v={...old,homeScore:h===''?null:+h,awayScore:a===''?null:+a,status:s};await set(ref(db,'matches/'+id),v);matches[id]=v;$('matchesMsg').textContent=id+' tersimpan. Klik Hitung dari Hasil untuk memperbarui klasemen.';setTimeout(()=>$('matchesMsg').textContent='',3000)};
onAuthStateChanged(auth,async user=>{if(user&&user.email===ADMIN_EMAIL){show();await load()}else hide()});
