import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getDatabase,ref,get,onValue}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id);
const GROUPS=["A","B","C","D"],DEFAULT=Array.from({length:16},(_,i)=>`Tim ${i+1}`);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let teams={},groups={A:["","","",""],B:["","","",""],C:["","","",""],D:["","","",""]},matches={};
const pairings={1:[[0,1],[2,3]],2:[[0,2],[1,3]],3:[[0,3],[1,2]]};
const dates=[["2026-09-06","16:00"],["2026-09-12","13:30"],["2026-09-12","16:00"],["2026-09-13","08:00"],["2026-09-13","10:30"],["2026-09-13","13:30"],["2026-09-13","16:00"],["2026-09-19","13:30"],["2026-09-19","16:00"],["2026-09-20","08:00"],["2026-09-20","10:30"],["2026-09-20","13:30"],["2026-09-20","16:00"],["2026-09-26","13:30"],["2026-09-26","16:00"],["2026-09-27","08:00"],["2026-09-27","10:30"],["2026-09-27","13:30"],["2026-09-27","16:00"],["2026-10-03","13:30"],["2026-10-03","16:00"],["2026-10-04","08:00"],["2026-10-04","10:30"],["2026-10-04","13:30"]];
function tname(id){return teams[id]?.name||id||"Belum dipilih"}
function normalize(v){const o={A:["","","",""],B:["","","",""],C:["","","",""],D:["","","",""]};for(const g of GROUPS){const s=v?.[g];if(Array.isArray(s))o[g]=s.slice(0,4).map(x=>x||"");else if(s)for(let i=0;i<4;i++)o[g][i]=s[i]||""}return o}
function calc(g){const r={};(groups[g]||[]).forEach(id=>{if(id)r[id]={id,name:tname(id),mp:0,w:0,d:0,l:0,gm:0,gk:0,pts:0}});Object.values(matches).filter(m=>m?.phase==="group"&&m.group===g).forEach(m=>{if(!m.home||!m.away||m.homeScore==null||m.awayScore==null||!r[m.home]||!r[m.away])return;const hs=Number(m.homeScore),as=Number(m.awayScore);if(!Number.isFinite(hs)||!Number.isFinite(as))return;const h=r[m.home],a=r[m.away];h.mp++;a.mp++;h.gm+=hs;h.gk+=as;a.gm+=as;a.gk+=hs;if(hs>as){h.w++;a.l++;h.pts+=3}else if(hs<as){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}});return Object.values(r).sort((a,b)=>b.pts-a.pts||(b.gm-b.gk)-(a.gm-a.gk)||b.gm-a.gm)}
function render(){
 const tl=$("teamList");if(tl)tl.innerHTML=Array.from({length:16},(_,i)=>`<div class="team">${i+1}. ${esc(tname("T"+(i+1)))}</div>`).join("");
 const tab=$("tables");if(tab)tab.innerHTML=GROUPS.map(g=>{const rows=calc(g);return `<div class="card"><h3>Grup ${g}</h3><div class="tablewrap"><table><thead><tr><th>Pos</th><th>Tim</th><th>Main</th><th>Menang</th><th>Seri</th><th>Kalah</th><th>GM</th><th>GK</th><th>SG</th><th>Poin</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td><b>${esc(r.name)}</b></td><td>${r.mp}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gm}</td><td>${r.gk}</td><td>${r.gm-r.gk}</td><td><b>${r.pts}</b></td></tr>`).join("")}</tbody></table></div></div>`}).join("");
 const mm=Object.values(matches).filter(m=>m?.phase==="group").sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));const list=$("matches");if(list)list.innerHTML=mm.map((m,i)=>`<div class="match"><div><div class="date">PERTANDINGAN ${i+1} • PUTARAN ${m.round} • GRUP ${m.group}</div><div class="teamscore">${esc(tname(m.home))} <b>vs</b> ${esc(tname(m.away))}</div><div class="date">${esc(m.date||"")} • ${esc(m.time||"")} WIB</div></div><div><b>${m.homeScore??"-"} : ${m.awayScore??"-"}</b><div class="label">${m.status==="finished"?"SELESAI":m.status==="live"?"LIVE":"TERJADWAL"}</div></div></div>`).join("");
 const next=mm.find(m=>m.status!=="finished"&&m.home&&m.away)||mm[0],nm=$("nextMatch");if(nm&&next)nm.innerHTML=`<div class="card"><div class="teamscore">${esc(tname(next.home))} <b>vs</b> ${esc(tname(next.away))}</div><div class="date">Grup ${next.group} • ${next.date||""} • ${next.time||""} WIB</div></div>`;
}
async function load(){try{const [ts,gs,ms]=await Promise.all([get(ref(db,"teams")),get(ref(db,"groups")),get(ref(db,"matches"))]);const tv=ts.exists()?ts.val():{};teams={};for(let i=1;i<=16;i++){const id="T"+i;teams[id]={name:tv[id]?.name||tv[id]||DEFAULT[i-1]}};groups=gs.exists()?normalize(gs.val()):groups;matches=ms.exists()?ms.val():{};render()}catch(e){console.error("LigaKita public load:",e)}}
load();onValue(ref(db,"teams"),load);onValue(ref(db,"groups"),load);onValue(ref(db,"matches"),load);
